In [81]:
import tensorflow as tf
import numpy as np

In [14]:
MAX_WORD = 30000
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=MAX_WORD)

In [15]:
tf.executing_eagerly()

True

In [28]:
x = [[2,3], [1, 4]]
y = [[1,2], [2, 1]]

In [29]:
m = tf.matmul(x, y)

In [30]:
m.numpy()

array([[8, 7],
       [9, 6]], dtype=int32)

In [31]:
m = tf.multiply(x, y)

In [32]:
m

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 6],
       [2, 4]], dtype=int32)>

In [33]:
num = tf.convert_to_tensor(10)

tensor对象和可以和numpy自动做转换

In [45]:
# 定义常量
a = tf.constant([[10,20], [1,3]])
b = [[1, 2], [4,4]]
m = tf.matmul(a, b)

In [57]:
# 定义变量
a = tf.Variable(0.0,)
a.assign(10)
a.read_value()

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [61]:
a = tf.constant([[1,2,3], [3,4,5]])
a = tf.constant([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [65]:
a = tf.Variable([[1,2]])
# 返回变量的维度
tf.rank(a)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [68]:
c = tf.constant([1.0,2.0])
print(tf.rank(c))
print(id(c))

tf.Tensor(1, shape=(), dtype=int32)
26971061952


In [69]:
c = tf.constant([1.0,2.0])
print(c)
print(id(c))
c = c + tf.constant([1.0,1.0])
print(c)
print(id(c))

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
26971061424
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
26971061072


In [80]:
a = tf.Variable([1.0,2.0],name = "a").read_value()
print(a)
b = tf.Variable([2.0,3.0],name = "b")
c = tf.scalar_mul(tf.constant(2.0), b)

tf.Tensor([1. 2.], shape=(2,), dtype=float32)


In [77]:
a = 10
id(a)


4433114528

In [79]:
a = 11
id(a)

4433114560

tensorflow的自动微分机制

In [86]:
x = tf.Variable(0.0, name="x", dtype=tf.float32)
a = tf.constant(1.0)
b = tf.constant(-2.0)
c = tf.constant(1.0)
with tf.GradientTape() as tape:
    y = a*tf.pow(x,2) + b*x + c
dy_dx = tape.gradient(y,x)
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [84]:
# 对常量张量也可以求导，需要增加watch，确保被跟踪
with tf.GradientTape() as tape:
    tape.watch([a,b,c])
    y = a*tf.pow(x,2) + b*x + c
    
dy_dx,dy_da,dy_db,dy_dc = tape.gradient(y,[x,a,b,c])
print(dy_da)
print(dy_dc)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [93]:
with tf.GradientTape() as tape2:
    with tf.GradientTape() as tape1:
        y = a*tf.pow(x,2) + b*x + c
    dy_dx = tape1.gradient(y,x)
dy2_dx2=  tape2.gradient(dy_dx,x)
dy2_dx2

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [99]:
@tf.function
def f(b):
    a = tf.constant([[10,10],[11.,1.]])
    x = tf.constant([[1.,0.],[0.,1.]])
    y = tf.matmul(a, x) * b * 1
    print("PRINT: ", y)
    tf.print("TF-PRINT: ", y)
    return y

b = tf.Variable(12.)
f(b)

PRINT:  Tensor("mul_1:0", shape=(2, 2), dtype=float32)
TF-PRINT:  [[120 120]
 [132 12]]


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[120., 120.],
       [132.,  12.]], dtype=float32)>

In [101]:
a = tf.Variable(0)

@tf.function
def g(x):
    x.assign_add(1)
    return x

print(g(a))
print(g(a))
print(g(a))
a

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [119]:
tf.print(tf.constant(10))

10


In [120]:
@tf.function
def f(x):   
    a = tf.constant(1.0)
    b = tf.constant(-2.0)
    c = tf.constant(1.0)
    
    # 自变量转换成tf.float32
    x = tf.cast(x,tf.float32)
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = a*tf.pow(x,2)+b*x+c
    dy_dx = tape.gradient(y,x) 
    
    return((dy_dx,y))

tf.print(f(tf.constant(0.0)))
tf.print(f(tf.constant(1.0)))

(-2, 1)
(0, 0)


In [123]:
x = tf.Variable(1.0)
with tf.GradientTape(persistent=True) as tape:
    y = x * x
    w = x * x
a = tape.gradient(y, x)
b = tape.gradient(w, x)
b

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>